WIN_WIDTH = 750
WIN_HEIGHT = 570

PLAYER_LAYER = 4
ENEMY_LAYER = 2
BLOCK_LAYER = 1
GROUND_LAYER = 1
DOOR_LAYER = 4
COIN_LAYER = 3
TILESIZE = 30
ENEMY_SPEED = 3
PLAYER_SPEED = 2
RED = (255, 0, 0)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
FPS = 60
SCORES = 0
tilemap = [
    'LLLLLLLLLDLLLLLLLLLLLLLLL',
    'LBBBBB..BCB..BBBBBL.....L',
    'LBECCB..BCB..BECCBL.....L',
    'LBCBCB..BCB..BCBCBL.....L',
    'LBCCCB..E....BCCCBL.....L',
    'LBB.BB.BBBBB.BB.BBL.....L',
    'LE..C..CCCCC..C..EL.....L',
    'L...CB.BBBBB.BC...L.....L',
    'LBBBCB.BCECB.BCBBBL.....L',
    'D.PCCB.BCBCB.BCCCCD.....L',
    'LBBBCB.BC.CB.BCBBBL.....L',
    'L...CB.BB.BB.BC...L.....L',
    'L...C..CCCCC......L.....L',
    'LBB.BB.BBBBB.BB.BBL.....L',
    'LBECCB..E....BECCBL.....L',
    'LBCBCB..BCB..BCBCBL.....L',
    'LBCCCB..BCB..BCCCBL.....L',
    'LBBBBB..BCB..BBBBBL.....L',
    'LLLLLLLLLDLLLLLLLLLLLLLLL'
]
